/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        aion: {
          dark: '#0B1B3D',
          primary: '#1A5490',
          blue: '#2E75B6',
          cyan: '#00D4FF',
        },
        // Design system palette
        'on-surface': '#1a1a2e',
        'outline-variant': '#c3c6d2',
        'outline': '#737781',
        'surface-bright': '#fcf8ff',
        'background': '#fcf8ff',
        'surface-tint': '#325ea0',
        'surface-container-high': '#e8e5ff',
        'primary-fixed': '#d6e3ff',
        'surface': '#fcf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f2ff',
        'primary': '#00346d',
        'primary-container': '#1a4b8c',
        'secondary': '#205db0',
        'secondary-container': '#73a6fe',
        'secondary-fixed': '#d7e3ff',
        'on-secondary-fixed': '#001b3f',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#434750',
        'on-primary-fixed-variant': '#124687',
        'surface-container': '#efecff',
        'surface-container-highest': '#e2e0fc',
        'inverse-surface': '#2f2e43',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface-dim': '#dad7f3',
        'inverse-primary': '#aac7ff',
        'inverse-on-surface': '#f2efff',
        'on-primary-fixed': '#001b3e',
        'on-secondary-container': '#003a7a',
        'surface-variant': '#e2e0fc',
        'secondary-fixed-dim': '#abc7ff',
        'primary-fixed-dim': '#aac7ff',
        'on-background': '#1a1a2e',
        'green': '#1d9e75',
        'amber': '#ba7517',
        'coral': '#d85a30',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Inter'],
        body: ['Inter'],
        label: ['Inter'],
      },
      letterSpacing: {
        'editorial': '-0.05em',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
